import sample from 'lodash.sample';

export const randomImagePrompts = [
  'A magical steampunk train chugging through a fantastical desert landscape with mechanical sandstorms',
  'An ancient temple hidden deep within a lush jungle, guarded by mythical creatures',
  'A futuristic underwater research facility exploring the depths of the ocean for undiscovered species',
  'A sprawling space station orbiting a distant planet, bustling with alien traders and explorers',
  'A floating island paradise with waterfalls cascading into crystal-clear lagoons surrounded by tropical forests',
  'A whimsical village built on the back of a giant turtle, drifting through the cosmos',
  'A cybernetic gladiator arena where robotic warriors battle for supremacy in a post-apocalyptic world',
  'A magical library filled with books that come to life, revealing their secrets to those who dare to read them',
  'A time-traveling pirate ship sailing through the skies, raiding airships and plundering treasure',
  'An enchanted garden inhabited by fairies, with glowing flowers and hidden paths leading to secret realms',
  'A floating city in the clouds, with airships docking at towering skyscrapers and floating markets bustling with activity',
  'A group of intergalactic explorers discovering a lost civilization on the surface of a distant planet',
  'A fantastical circus with acrobats, clowns, and performers from different dimensions delighting the audience',
  'A magical portal hidden in an ancient stone circle, leading to realms beyond imagination',
  'A giant treehouse village nestled in the branches of an ancient forest, home to a community of tree-dwelling creatures',
  'A steampunk laboratory filled with bubbling vials, sparking machinery, and eccentric inventors',
  'A mystical desert oasis surrounded by towering sand dunes and inhabited by nomadic tribes',
  'A mythical creature sanctuary floating on a cloud, where legendary beasts find refuge from the mortal world',
  'A cosmic carnival on the edge of the universe, with rides that defy gravity and games of chance played with celestial objects',
  'A secret underwater cave filled with glowing crystals and inhabited by mermaids and sea monsters',
  'An abandoned space station overrun by alien flora and fauna, with remnants of a long-forgotten civilization',
  'A parallel dimension where dinosaurs still roam the earth, coexisting with futuristic technology',
  'A haunted shipwreck at the bottom of the ocean, with ghostly sailors haunting its corridors',
  'A labyrinthine city of gears and cogs, where clockwork creatures roam the streets',
  'A mythical mountain range shrouded in mist, home to dragons and other legendary beasts',
  'A floating marketplace in the sky, where traders from different worlds come to barter goods and stories',
  'An ancient coliseum in ruins, where echoes of gladiator battles can still be heard',
  'A hidden valley untouched by time, where prehistoric creatures roam amidst towering ferns and ancient trees',
  'A magical ice palace at the heart of a frozen kingdom, ruled by a snow queen',
  'An alien bazaar on a distant planet, with strange and exotic goods for sale',
  'A celestial observatory perched on the edge of the universe, where astronomers study the birth of stars',
  'A secret garden hidden behind a waterfall, filled with rare and exotic plants',
  'A futuristic utopia where humans and robots live together in harmony, governed by artificial intelligence',
  'A mythical city of Atlantis rising from the depths of the ocean, its gleaming spires reaching for the sky',
  'An enchanted forest where the trees whisper secrets and the animals hold court',
  'A floating fortress in the clouds, defended by airships and flying dragons',
  'A steampunk metropolis powered by steam and gears, with towering factories belching smoke into the sky',
  'A hidden cave filled with ancient cave paintings and artifacts from lost civilizations',
  'A cosmic highway stretching across the universe, connecting distant galaxies and civilizations',
  'A futuristic coliseum where robots battle for the entertainment of their human masters',
  'A magical marketplace filled with potions, charms, and enchanted artifacts',
  'An abandoned space colony reclaimed by nature, with vines and trees growing through its abandoned buildings',
  'A mythical labyrinth guarded by minotaurs and other mythical creatures',
  'A floating city made entirely of crystals, reflecting rainbows in every direction',
  'An underwater graveyard of sunken ships, haunted by the ghosts of sailors lost at sea',
  'A steampunk circus with mechanical animals, steam-powered performers, and a clockwork ringmaster',
  'A celestial palace on the moon, where gods and goddesses reside',
  'An ancient ruin hidden beneath the sands of the desert, waiting to be rediscovered',
  'A futuristic megacity where skyscrapers reach into the clouds and hovercars zoom through the streets',
  'A mystical waterfall that flows upwards into the sky, defying gravity',
  'A hidden cavern filled with glowing mushrooms and bioluminescent creatures',
  'A cosmic library containing the knowledge of the universe, guarded by celestial beings',
  'An enchanted lake inhabited by nymphs and water spirits, with waters that grant eternal youth',
  'A futuristic theme park where visitors can travel through time and space',
  'A mythical kingdom ruled by a wise and just queen, with knights and dragons protecting its borders',
  'A secret laboratory hidden in the depths of a volcano, where mad scientists conduct experiments',
  'A parallel universe where magic and technology coexist, creating a world of endless possibilities',
  'A mystical tree that holds the balance of the universe, with roots that reach into the depths of the earth and branches that touch the stars',
  'An alien marketplace filled with strange and exotic goods from across the galaxy',
  'A floating island inhabited by giant insects and other oversized creatures',
  'A haunted forest where the trees move and the shadows whisper',
  'A futuristic battlefield where humans and robots fight for control of the planet',
  'An underwater city built by ancient civilizations, now inhabited by merfolk and sea monsters',
  'A mythical city hidden in the clouds, accessible only to those who can fly',
  'A steampunk submarine exploring the depths of the ocean, encountering strange creatures and lost civilizations',
  'A cosmic circus traveling through space, entertaining audiences on distant planets',
  'An enchanted castle surrounded by a magical forest, protected by spells and enchantments',
  'A futuristic prison on a distant planet, with inmates kept in suspended animation',
  'A secret society of wizards and witches hidden within the walls of an ordinary city',
  'A mythical realm where dreams and nightmares come to life',
  'A floating city of airships, with markets, theaters, and homes suspended in the sky',
  'A hidden oasis in the desert, with palm trees and cool waters amidst the sand dunes',
  'A futuristic colony on Mars, with domed cities and terraformed landscapes',
  'A mystical portal hidden in the heart of a volcano, leading to other dimensions',
  'A cosmic dance party on the surface of the moon, with aliens and astronauts grooving to the music',
  'An enchanted forest where time moves differently, with trees that grow and shrink with the passing of the seasons',
  'A futuristic amusement park on a distant planet, with rides and attractions unlike anything on Earth',
  'A futuristic cityscape at dusk with neon lights reflecting off rain-soaked streets',
  'A whimsical forest scene with talking animals having a tea party under a giant mushroom',
  'An astronaut exploring a mysterious alien planet filled with bioluminescent flora and fauna',
  'A steampunk airship floating above a bustling Victorian-era city skyline',
  'A serene mountain lake surrounded by towering pine trees and snow-capped peaks',
  'A group of fantastical creatures playing a game of soccer in a magical meadow',
  'A cybernetic samurai dueling with a giant robotic serpent in a neon-lit alleyway',
  'A mystical wizard conjuring a storm of colorful energy in a hidden library of ancient spells',
  'A post-apocalyptic wasteland reclaimed by nature, with ruins of skyscrapers overgrown with vines',
  'A magical carnival with flying carousel horses and cotton candy clouds in the sky',
  'An underwater city inhabited by mermaids and sea creatures, with coral reefs and sunken ships',
  'A time-traveling adventurer riding a mechanical dragon through a portal to a parallel universe',
  'A surreal dreamscape with floating islands, giant floating eyes, and rainbow waterfalls',
  'A cosmic explorer discovering a hidden galaxy inside a swirl of interstellar dust',
  'A haunted mansion with ghostly figures peeking out from behind cracked windows and ivy-covered walls',
  'A futuristic metropolis where flying cars zoom between skyscrapers and holographic advertisements light up the sky',
  'A group of intrepid explorers traversing a dense jungle filled with ancient ruins and exotic wildlife',
  'An enchanted forest with glowing mushrooms, fireflies, and a mysterious glowing orb at its center',
  'A parallel universe where gravity works in reverse, with floating islands and upside-down cities',
  'A magical school for young wizards and witches, with turrets, towers, and flying broomsticks',
  'A fantastical underwater kingdom ruled by a wise and ancient sea turtle',
  'A dystopian cityscape with towering skyscrapers and polluted skies, where rebels fight against oppressive regimes',
  'A celestial battlefield where angels and demons clash amidst swirling galaxies and cosmic storms',
  'A whimsical village inhabited by anthropomorphic animals, with colorful houses and cobblestone streets',
  'A mythical creature sanctuary hidden deep within a mystical forest, where unicorns, dragons, and griffins roam freely',
];

export default function getRandomPrompt() {
  return sample(randomImagePrompts);
}
